version: '3.8'

services:
  # Service MongoDB
  mongodb_service:
    image: mongo:5.0
    container_name: mongodb_service_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - custom_network

  # Service Python pour exécuter mongodb_crud.py
  python_application:
    build:
      context: ../  # Remonter d'un répertoire pour accéder au Dockerfile
      dockerfile: docker/Dockerfile
    container_name: python_application_container
    depends_on:
      - mongodb_service
    volumes:
      - ../scripts:/app/scripts  # Volume pour mapper les scripts
      - ../data:/app/data  # Volume pour mapper les données
    networks:
      - custom_network

volumes:
  mongodb_data:
    driver: local

networks:
  custom_network:
    driver: bridge
